server.port: 8081

spring.data.mongodb:
  host: 127.0.0.1
  port: 27017
  database: train
#  username: test
#  password: 123456

cn.axboy.train:
  train:
    getStationUrl:    https://kyfw.12306.cn/otn/resources/js/framework/station_name.js?station_version=1.9046
    queryInitUrl:     https://kyfw.12306.cn/otn/leftTicket/init
    queryTicketUrl:   https://kyfw.12306.cn/otn/leftTicket/queryZ

  cert:
    srcaKeyStore: classpath:cert/srca.keystore
    srcaPassword: 123456

  qiNiu:
    accessKey: todo
    secretKey: todo
    bucket: todo
    prefix: todo

  dama2:
    appId: todo
    appKey: todo
    username: todo
    password: todo
    solveByImgFile: http://api.dama2.com:7766/app/d2File
    solveByImgUrl: http://api.dama2.com:7766/app/d2Url